import { create } from "zustand";
import { persist } from "zustand/middleware";

export interface Product {
  id: string;
  name: string;
  price: number;
  inStock: boolean;
  category: string;
  brand: string;
  status: "Available" | "Out of Stock" | "Coming Soon";
  quantity: number;
  color: string;
  sku: string;
  rating: number;
  image?: string;
}

interface ProductState {
  products: Product[];
  addProduct: (product: Omit<Product, "id">) => void;
  getProductBySku: (sku: string) => Product | undefined;
}

export const useProductStore = create<ProductState>()(
  persist(
    (set, get) => ({
      products: [
        {
          id: "1",
          name: "Apple iPhone 15 Pro",
          price: 999,
          inStock: true,
          category: "Electronics",
          brand: "Apple",
          status: "Available",
          quantity: 50,
          color: "Titanium",
          sku: "IPH15PRO-TIT",
          rating: 4.8,
          image:
            "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400",
        },
        {
          id: "2",
          name: "Samsung Galaxy S24 Ultra",
          price: 1199,
          inStock: true,
          category: "Electronics",
          brand: "Samsung",
          status: "Available",
          quantity: 35,
          color: "Phantom Black",
          sku: "SGS24U-BLK",
          rating: 4.7,
          image:
            "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400",
        },
        {
          id: "3",
          name: "Sony WH-1000XM5 Headphones",
          price: 399,
          inStock: true,
          category: "Electronics",
          brand: "Sony",
          status: "Available",
          quantity: 100,
          color: "Black",
          sku: "SNYWH1000XM5",
          rating: 4.9,
          image:
            "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400",
        },
        {
          id: "4",
          name: 'MacBook Pro 16"',
          price: 2499,
          inStock: true,
          category: "Electronics",
          brand: "Apple",
          status: "Available",
          quantity: 20,
          color: "Space Gray",
          sku: "MBP16-SG",
          rating: 4.8,
          image:
            "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
        },
        {
          id: "5",
          name: "Nike Air Max 2024",
          price: 150,
          inStock: true,
          category: "Clothing",
          brand: "Nike",
          status: "Available",
          quantity: 200,
          color: "White",
          sku: "NKAIRMAX24-WHT",
          rating: 4.5,
          image:
            "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        },
        {
          id: "6",
          name: "Adidas Ultraboost 23",
          price: 180,
          inStock: false,
          category: "Clothing",
          brand: "Adidas",
          status: "Out of Stock",
          quantity: 0,
          color: "Core Black",
          sku: "ADIUB23-BLK",
          rating: 4.6,
          image:
            "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400",
        },
        {
          id: "7",
          name: "Dell XPS 15",
          price: 1799,
          inStock: true,
          category: "Electronics",
          brand: "Dell",
          status: "Available",
          quantity: 15,
          color: "Platinum Silver",
          sku: "DELLXPS15-PT",
          rating: 4.6,
          image:
            "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400",
        },
        {
          id: "8",
          name: "IKEA KALLAX Shelf",
          price: 89,
          inStock: true,
          category: "Furniture",
          brand: "IKEA",
          status: "Available",
          quantity: 75,
          color: "White",
          sku: "IKEA-KALLAX-WHT",
          rating: 4.3,
          image:
            "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
        },
        {
          id: "9",
          name: "Herman Miller Aeron Chair",
          price: 1395,
          inStock: true,
          category: "Furniture",
          brand: "Herman Miller",
          status: "Available",
          quantity: 10,
          color: "Graphite",
          sku: "HM-AERON-GRP",
          rating: 4.9,
          image:
            "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400",
        },
        {
          id: "10",
          name: 'LG OLED C3 65"',
          price: 2199,
          inStock: true,
          category: "Electronics",
          brand: "LG",
          status: "Available",
          quantity: 8,
          color: "Black",
          sku: "LG-OLEDC3-65",
          rating: 4.8,
          image:
            "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400",
        },
        {
          id: "11",
          name: "Canon EOS R5",
          price: 3899,
          inStock: true,
          category: "Electronics",
          brand: "Canon",
          status: "Available",
          quantity: 12,
          color: "Black",
          sku: "CANON-R5-BLK",
          rating: 4.9,
          image:
            "https://images.unsplash.com/photo-1606980645320-acb6e1c8809d?w=400",
        },
        {
          id: "12",
          name: "Dyson V15 Detect",
          price: 649,
          inStock: true,
          category: "Electronics",
          brand: "Dyson",
          status: "Available",
          quantity: 30,
          color: "Nickel",
          sku: "DYSON-V15-NCL",
          rating: 4.7,
          image:
            "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400",
        },
        {
          id: "13",
          name: "Levi's 501 Original Jeans",
          price: 98,
          inStock: true,
          category: "Clothing",
          brand: "Levi's",
          status: "Available",
          quantity: 150,
          color: "Blue Denim",
          sku: "LEVIS-501-BLU",
          rating: 4.4,
          image:
            "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
        },
        {
          id: "14",
          name: "North Face Nuptse Jacket",
          price: 349,
          inStock: true,
          category: "Clothing",
          brand: "The North Face",
          status: "Available",
          quantity: 40,
          color: "Black",
          sku: "TNF-NUPTSE-BLK",
          rating: 4.8,
          image:
            "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
        },
        {
          id: "15",
          name: "West Elm Mid-Century Sofa",
          price: 1499,
          inStock: true,
          category: "Furniture",
          brand: "West Elm",
          status: "Available",
          quantity: 5,
          color: "Charcoal",
          sku: "WE-MCSOFA-CHR",
          rating: 4.6,
          image:
            "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
        },
        {
          id: "16",
          name: "Nintendo Switch OLED",
          price: 349,
          inStock: true,
          category: "Electronics",
          brand: "Nintendo",
          status: "Available",
          quantity: 60,
          color: "White",
          sku: "NSW-OLED-WHT",
          rating: 4.7,
          image:
            "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400",
        },
        {
          id: "17",
          name: "PlayStation 5",
          price: 499,
          inStock: false,
          category: "Electronics",
          brand: "Sony",
          status: "Out of Stock",
          quantity: 0,
          color: "White",
          sku: "PS5-WHT",
          rating: 4.8,
          image:
            "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400",
        },
        {
          id: "18",
          name: "Bose SoundLink Revolve+",
          price: 329,
          inStock: true,
          category: "Electronics",
          brand: "Bose",
          status: "Available",
          quantity: 45,
          color: "Triple Black",
          sku: "BOSE-SLRP-BLK",
          rating: 4.6,
          image:
            "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400",
        },
        {
          id: "19",
          name: "Patagonia Better Sweater",
          price: 139,
          inStock: true,
          category: "Clothing",
          brand: "Patagonia",
          status: "Available",
          quantity: 80,
          color: "Stonewash",
          sku: "PAT-BSWE-STN",
          rating: 4.7,
          image:
            "https://images.unsplash.com/photo-1434510423563-4ec49a0b4b7a?w=400",
        },
        {
          id: "20",
          name: "Zara Slim Fit Blazer",
          price: 129,
          inStock: true,
          category: "Clothing",
          brand: "Zara",
          status: "Available",
          quantity: 70,
          color: "Navy",
          sku: "ZARA-BLZR-NVY",
          rating: 4.2,
          image:
            "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400",
        },
        {
          id: "21",
          name: 'Samsung 49" Odyssey G9',
          price: 1399,
          inStock: true,
          category: "Electronics",
          brand: "Samsung",
          status: "Available",
          quantity: 15,
          color: "Black",
          sku: "SAM-ODG9-BLK",
          rating: 4.7,
          image:
            "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=400",
        },
        {
          id: "22",
          name: "Logitech MX Master 3S",
          price: 99,
          inStock: true,
          category: "Electronics",
          brand: "Logitech",
          status: "Available",
          quantity: 120,
          color: "Graphite",
          sku: "LOG-MXM3S-GRP",
          rating: 4.8,
          image:
            "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
        },
        {
          id: "23",
          name: "Keychron K8 Pro",
          price: 109,
          inStock: true,
          category: "Electronics",
          brand: "Keychron",
          status: "Available",
          quantity: 90,
          color: "Carbon Black",
          sku: "KEY-K8PRO-BLK",
          rating: 4.6,
          image:
            "https://images.unsplash.com/photo-1595225476474-87563907a212?w=400",
        },
        {
          id: "24",
          name: "Herman Miller Embody",
          price: 1795,
          inStock: true,
          category: "Furniture",
          brand: "Herman Miller",
          status: "Available",
          quantity: 7,
          color: "Charcoal",
          sku: "HM-EMBODY-CHR",
          rating: 4.9,
          image:
            "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=400",
        },
        {
          id: "25",
          name: "IKEA BEKANT Desk",
          price: 249,
          inStock: true,
          category: "Furniture",
          brand: "IKEA",
          status: "Available",
          quantity: 40,
          color: "White",
          sku: "IKEA-BEKANT-WHT",
          rating: 4.1,
          image:
            "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400",
        },
        {
          id: "26",
          name: "Apple AirPods Pro 2",
          price: 249,
          inStock: true,
          category: "Electronics",
          brand: "Apple",
          status: "Available",
          quantity: 150,
          color: "White",
          sku: "APP-PRO2-WHT",
          rating: 4.7,
          image:
            "https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=400",
        },
        {
          id: "27",
          name: "Instant Pot Duo Plus",
          price: 119,
          inStock: true,
          category: "Electronics",
          brand: "Instant Pot",
          status: "Available",
          quantity: 65,
          color: "Stainless Steel",
          sku: "IP-DUO-SS",
          rating: 4.6,
          image:
            "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400",
        },
        {
          id: "28",
          name: "KitchenAid Stand Mixer",
          price: 449,
          inStock: true,
          category: "Electronics",
          brand: "KitchenAid",
          status: "Available",
          quantity: 30,
          color: "Empire Red",
          sku: "KA-MIX-RED",
          rating: 4.8,
          image:
            "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400",
        },
        {
          id: "29",
          name: "Ninja Foodi Air Fryer",
          price: 199,
          inStock: true,
          category: "Electronics",
          brand: "Ninja",
          status: "Available",
          quantity: 55,
          color: "Black",
          sku: "NINJA-AF-BLK",
          rating: 4.5,
          image:
            "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400",
        },
        {
          id: "30",
          name: "Yeti Rambler 30oz",
          price: 38,
          inStock: true,
          category: "Electronics",
          brand: "Yeti",
          status: "Available",
          quantity: 200,
          color: "Navy",
          sku: "YETI-RAM30-NVY",
          rating: 4.9,
          image:
            "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400",
        },
        {
          id: "31",
          name: "Uniqlo Heattech Shirt",
          price: 29,
          inStock: true,
          category: "Clothing",
          brand: "Uniqlo",
          status: "Available",
          quantity: 300,
          color: "Black",
          sku: "UNI-HEAT-BLK",
          rating: 4.3,
          image:
            "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
        },
        {
          id: "32",
          name: "H&M Cotton T-Shirt",
          price: 12,
          inStock: true,
          category: "Clothing",
          brand: "H&M",
          status: "Available",
          quantity: 400,
          color: "White",
          sku: "HM-TEE-WHT",
          rating: 3.9,
          image:
            "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
        },
        {
          id: "33",
          name: "Carhartt Work Jacket",
          price: 179,
          inStock: true,
          category: "Clothing",
          brand: "Carhartt",
          status: "Available",
          quantity: 60,
          color: "Brown",
          sku: "CAR-WJKT-BRN",
          rating: 4.7,
          image:
            "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
        },
        {
          id: "34",
          name: "Fjallraven Kanken Backpack",
          price: 85,
          inStock: true,
          category: "Clothing",
          brand: "Fjallraven",
          status: "Available",
          quantity: 110,
          color: "Fog",
          sku: "FJALL-KANK-FOG",
          rating: 4.5,
          image:
            "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        },
        {
          id: "35",
          name: "Ray-Ban Aviator Classic",
          price: 163,
          inStock: true,
          category: "Clothing",
          brand: "Ray-Ban",
          status: "Available",
          quantity: 85,
          color: "Gold",
          sku: "RB-AVI-GLD",
          rating: 4.6,
          image:
            "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400",
        },
        {
          id: "36",
          name: "MUJI Desk Organizer",
          price: 24,
          inStock: true,
          category: "Furniture",
          brand: "MUJI",
          status: "Available",
          quantity: 180,
          color: "Clear",
          sku: "MUJI-ORG-CLR",
          rating: 4.4,
          image:
            "https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?w=400",
        },
        {
          id: "37",
          name: "Crate & Barrel Bookshelf",
          price: 599,
          inStock: true,
          category: "Furniture",
          brand: "Crate & Barrel",
          status: "Available",
          quantity: 18,
          color: "Oak",
          sku: "CB-BOOK-OAK",
          rating: 4.5,
          image:
            "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400",
        },
        {
          id: "38",
          name: "Article Sven Sofa",
          price: 2199,
          inStock: true,
          category: "Furniture",
          brand: "Article",
          status: "Available",
          quantity: 6,
          color: "Charcoal Gray",
          sku: "ART-SVEN-GRY",
          rating: 4.7,
          image:
            "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
        },
        {
          id: "39",
          name: "Floyd Platform Bed",
          price: 1095,
          inStock: true,
          category: "Furniture",
          brand: "Floyd",
          status: "Available",
          quantity: 12,
          color: "Birch",
          sku: "FLD-BED-BIR",
          rating: 4.6,
          image:
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400",
        },
        {
          id: "40",
          name: "CB2 Acrylic Coffee Table",
          price: 399,
          inStock: true,
          category: "Furniture",
          brand: "CB2",
          status: "Available",
          quantity: 25,
          color: "Clear",
          sku: "CB2-ACRY-CLR",
          rating: 4.3,
          image:
            "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=400",
        },
        {
          id: "41",
          name: "Apple Watch Series 9",
          price: 429,
          inStock: true,
          category: "Electronics",
          brand: "Apple",
          status: "Available",
          quantity: 95,
          color: "Midnight",
          sku: "AW9-MID",
          rating: 4.7,
          image:
            "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400",
        },
        {
          id: "42",
          name: "Garmin Fenix 7",
          price: 699,
          inStock: true,
          category: "Electronics",
          brand: "Garmin",
          status: "Available",
          quantity: 28,
          color: "Black",
          sku: "GAR-FNX7-BLK",
          rating: 4.8,
          image:
            "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400",
        },
        {
          id: "43",
          name: "iPad Air 5th Gen",
          price: 599,
          inStock: true,
          category: "Electronics",
          brand: "Apple",
          status: "Available",
          quantity: 42,
          color: "Starlight",
          sku: "IPADAIR5-STL",
          rating: 4.6,
          image:
            "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
        },
        {
          id: "44",
          name: "Amazon Echo Dot 5",
          price: 49,
          inStock: true,
          category: "Electronics",
          brand: "Amazon",
          status: "Available",
          quantity: 250,
          color: "Charcoal",
          sku: "AMZ-ECHO5-CHR",
          rating: 4.5,
          image:
            "https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?w=400",
        },
        {
          id: "45",
          name: "Google Nest Hub Max",
          price: 229,
          inStock: false,
          category: "Electronics",
          brand: "Google",
          status: "Coming Soon",
          quantity: 0,
          color: "Chalk",
          sku: "GOOG-NEST-CHK",
          rating: 4.4,
          image:
            "https://images.unsplash.com/photo-1558089687-5e5d25605257?w=400",
        },
      ],

      addProduct: (product) => {
        const newProduct: Product = {
          ...product,
          id: `prod_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        };
        set((state) => ({ products: [newProduct, ...state.products] }));
      },

      getProductBySku: (sku) => {
        return get().products.find(
          (p) => p.sku.toLowerCase() === sku.toLowerCase()
        );
      },
    }),
    {
      name: "product-storage",
    }
  )
);
